---
- name: Install necessary packages for fencing
  apt:
    name: git
    state: present
  become: yes

- name: Clone fence-agents repository
  git:
    repo: "https://github.com/ClusterLabs/fence-agents.git"
    dest: "/opt/fence-agents"
  become: yes

- name: Compile and install fence_vbox
  shell: ./configure && make && make install
  args:
    chdir: "/opt/fence-agents/agents/vbox"
  become: yes
